### ISSUE TITLE
[1.7.10] Compressor recipes can't be removed

### ISSUE THREAD

**Issue by Dream-Master** [SpitefulFox/Avaritia#116]
I try to rebalanced the Singualrities (how much Block needed) Sadly the remove code isnt supported and i not get why?

Using Avaritia 1.11 in a Modpack.
https://github.com/GTNewHorizons/NewHorizons

https://github.com/GTNewHorizons/NewHorizons/issues/1143

**Comment by SpitefulFox** [comment]
Compressor recipe removal IS supported.

**Comment by Dream-Master** [comment]
@SpitefulFox Ok maybe i using the wrong syntax?
I try this ``mods.avaritia.Compressor.remove(<Name of the Singulartiy>);``
It gives me an error and not load the whole script.
I send you the error message later when i am back on a computer.

**Comment by Dream-Master** [comment]
adding things works very well.

![image](https://cloud.githubusercontent.com/assets/2970688/23472872/8f8349ae-feae-11e6-8747-a523bb61d905.png)

addding removing code and using /mt reload through out this error:

``ERROR: Error executing Avaritia.zs: fox.spiteful.avaritia.crafting.ExtremeShapedRecipe cannot be cast to fox.spiteful.avaritia.crafting.CompressorRecipe
java.lang.ClassCastException: fox.spiteful.avaritia.crafting.ExtremeShapedRecipe cannot be cast to fox.spiteful.avaritia.crafting.CompressorRecipe
	at fox.spiteful.avaritia.compat.minetweaker.Compressor$Remove.apply(Compressor.java:95)
	at minetweaker.runtime.MTTweaker.apply(MTTweaker.java:65)
	at minetweaker.MineTweakerAPI.apply(MineTweakerAPI.java:176)
	at fox.spiteful.avaritia.compat.minetweaker.Compressor.remove(Compressor.java:39)
	at Avaritia.__script__(Avaritia.zs:67)
	at __ZenMain__.run(Avaritia.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:161)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:682)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:75)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:667)
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:116)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at fastcraft.at.a(F:978)
	at fastcraft.H.aq(F:36)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)``

**Comment by SpitefulFox** [comment]
Looks like a bug in the code.  I'll try and get this fixed when I have time.

**Comment by Dream-Master** [comment]
Thanks for look into it. I just fork your mod and change the values i need to change for my GTNH Modpack.
But maybe other will thank you for fixing.
