### ISSUE TITLE
Invalid registration attempt for an Ore Dictionary

### ISSUE THREAD

**Issue by Shoxxo** [SpitefulFox/Avaritia#127]
```
[23:03:33] [Server thread/WARN] [FML/Avaritia]: ****************************************
[23:03:33] [Server thread/WARN] [FML/Avaritia]: * Invalid registration attempt for an Ore Dictionary item with name blockCrystalMatrix has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[23:03:33] [Server thread/WARN] [FML/Avaritia]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:522)
[23:03:33] [Server thread/WARN] [FML/Avaritia]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[23:03:33] [Server thread/WARN] [FML/Avaritia]: *  at fox.spiteful.avaritia.crafting.Grinder.artsAndCrafts(Grinder.java:23)
[23:03:33] [Server thread/WARN] [FML/Avaritia]: *  at fox.spiteful.avaritia.Avaritia.midGame(Avaritia.java:69)
[23:03:33] [Server thread/WARN] [FML/Avaritia]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:03:33] [Server thread/WARN] [FML/Avaritia]: *  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[23:03:33] [Server thread/WARN] [FML/Avaritia]: ****************************************
[23:03:33] [Server thread/WARN] [FML/Avaritia]: ****************************************
[23:03:33] [Server thread/WARN] [FML/Avaritia]: * Invalid registration attempt for an Ore Dictionary item with name blockCosmicNeutronium has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[23:03:33] [Server thread/WARN] [FML/Avaritia]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:522)
[23:03:33] [Server thread/WARN] [FML/Avaritia]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[23:03:33] [Server thread/WARN] [FML/Avaritia]: *  at fox.spiteful.avaritia.crafting.Grinder.artsAndCrafts(Grinder.java:24)
[23:03:33] [Server thread/WARN] [FML/Avaritia]: *  at fox.spiteful.avaritia.Avaritia.midGame(Avaritia.java:69)
[23:03:33] [Server thread/WARN] [FML/Avaritia]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:03:33] [Server thread/WARN] [FML/Avaritia]: *  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[23:03:33] [Server thread/WARN] [FML/Avaritia]: ****************************************
[23:03:33] [Server thread/WARN] [FML/Avaritia]: ****************************************
[23:03:33] [Server thread/WARN] [FML/Avaritia]: * Invalid registration attempt for an Ore Dictionary item with name blockInfinity has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[23:03:33] [Server thread/WARN] [FML/Avaritia]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:522)
[23:03:33] [Server thread/WARN] [FML/Avaritia]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[23:03:33] [Server thread/WARN] [FML/Avaritia]: *  at fox.spiteful.avaritia.crafting.Grinder.artsAndCrafts(Grinder.java:25)
[23:03:33] [Server thread/WARN] [FML/Avaritia]: *  at fox.spiteful.avaritia.Avaritia.midGame(Avaritia.java:69)
[23:03:33] [Server thread/WARN] [FML/Avaritia]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:03:33] [Server thread/WARN] [FML/Avaritia]: *  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[23:03:33] [Server thread/WARN] [FML/Avaritia]: ****************************************
```

Version : Avaritia-1.11
OS : Linux Debian 9

**Comment by SpitefulFox** [comment]
Can you give me a little more info than this?  What mods are in the pack? Is this actually having any adverse effects or is it just a weird error in the log?
