### ISSUE TITLE
Exception on dedicated server start

### ISSUE THREAD

**Issue by LemADEC** [SpitefulFox/Avaritia#56]
Using Avaritia-0.2b.jar

When dedicated server starts, it appears the mod tries to use client side classes:
```
[08:58:16] [Server thread/INFO] [FML/Botania]: [Botania] The Lexica Botania has 25798 words.
[08:58:16] [Server thread/WARN] [/Avaritia]: java.lang.NoClassDefFoundError: net/minecraft/client/gui/inventory/GuiContainer
[08:58:16] [Server thread/WARN] [/Avaritia]:    at java.lang.Class.forName0(Native Method)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at java.lang.Class.forName(Class.java:195)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at fox.spiteful.avaritia.compat.Compat.compatify(Compat.java:57)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at fox.spiteful.avaritia.Avaritia.endGame(Avaritia.java:76)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at java.lang.reflect.Method.invoke(Method.java:606)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at java.lang.reflect.Method.invoke(Method.java:606)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at java.lang.reflect.Method.invoke(Method.java:606)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:324)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:287)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at java.lang.Thread.run(Thread.java:745)
[08:58:16] [Server thread/WARN] [/Avaritia]: Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.inventory.GuiContainer
[08:58:16] [Server thread/WARN] [/Avaritia]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[08:58:16] [Server thread/WARN] [/Avaritia]:    ... 35 more
[08:58:16] [Server thread/WARN] [/Avaritia]: Caused by: java.lang.RuntimeException: Attempted to load class bex for invalid side SERVER
[08:58:16] [Server thread/WARN] [/Avaritia]:    at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:51)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[08:58:16] [Server thread/WARN] [/Avaritia]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[08:58:16] [Server thread/WARN] [/Avaritia]:    ... 37 more
[08:58:16] [Server thread/INFO] [Mantle/Mantle]: Entering postinitialization phase.
[08:58:16] [Server thread/INFO] [Mantle/Mantle]: Loading Manual XML from: /assets/mantle/manuals/test.xml
```

**Comment by SpitefulFox** [comment]
Does the server actually have any problems or does this just appear in the log?

**Comment by LemADEC** [comment]
Server still starts, just not sure if the mod works properly yet

**Comment by SpitefulFox** [comment]
Then it's not a problem.  Mod is trying to add recipehandlers to NEI on server-side and failing.  Shouldn't be a problem since recipe lookups are client-side only anyway.
